/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex002;

import java.io.IOException;
import java.text.ParseException;
import java.time.Instant;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author franz
 */
public class WetterWerteGUI extends javax.swing.JFrame {

    /**
     * Creates new form WetterWerteGUI
     * 
     */
    private WetterModell m = new WetterModell();
    
    public WetterWerteGUI() {
        initComponents();
        liWerte.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbTemp = new javax.swing.JLabel();
        sTemp = new javax.swing.JSlider();
        lbLuft = new javax.swing.JLabel();
        sLuft = new javax.swing.JSlider();
        btAdd = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liWerte = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Eingabe"));
        jPanel2.setLayout(new java.awt.GridLayout(6, 0));

        lbTemp.setText("Temperatur: 40°");
        jPanel2.add(lbTemp);

        sTemp.setMajorTickSpacing(10);
        sTemp.setMaximum(40);
        sTemp.setMinimum(-20);
        sTemp.setMinorTickSpacing(5);
        sTemp.setPaintLabels(true);
        sTemp.setPaintTicks(true);
        sTemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onTempChange(evt);
            }
        });
        jPanel2.add(sTemp);

        lbLuft.setText("Luftfeuchtigkeit: 50%");
        jPanel2.add(lbLuft);

        sLuft.setMajorTickSpacing(20);
        sLuft.setMinorTickSpacing(10);
        sLuft.setPaintLabels(true);
        sLuft.setPaintTicks(true);
        sLuft.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onLuftChange(evt);
            }
        });
        jPanel2.add(sLuft);

        btAdd.setText("Einfügen");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEinfuegen(evt);
            }
        });
        jPanel2.add(btAdd);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Anzeige"));
        jPanel1.setLayout(new java.awt.GridLayout());

        jScrollPane1.setViewportView(liWerte);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1);

        jMenu1.setText("Datei");

        jMenuItem1.setText("Datei-speichern");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSpeichern(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Datei-laden");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLaden(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Datei-beenden");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onExit(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onExit
        System.exit(0);
    }//GEN-LAST:event_onExit

    private void onLaden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLaden
        try
        {
            m.loadDataTxt();   
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                ex,"Fehler - Load !!!",
                JOptionPane.ERROR_MESSAGE);
        } 
        
    }//GEN-LAST:event_onLaden

    private void onSpeichern(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSpeichern
        try { 
            m.saveDataTxt();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex,"Fehler bei Speichern!",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onSpeichern

    private void onEinfuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEinfuegen
        m.addWerte(new WetterWert(sTemp.getValue(), sLuft.getValue(), Date.from(Instant.now())));
    }//GEN-LAST:event_onEinfuegen

    private void onLuftChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onLuftChange
        lbLuft.setText("Luftfeuchtigkeit: "+sLuft.getValue()+"%");
    }//GEN-LAST:event_onLuftChange

    private void onTempChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onTempChange
        lbTemp.setText("Temperatur: "+sTemp.getValue()+"°");
    }//GEN-LAST:event_onTempChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WetterWerteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WetterWerteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLuft;
    private javax.swing.JLabel lbTemp;
    private javax.swing.JList<String> liWerte;
    private javax.swing.JSlider sLuft;
    private javax.swing.JSlider sTemp;
    // End of variables declaration//GEN-END:variables
}
